[package]
name = "heartbeat_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.32.0", features = ["full"] }
axum = { version = "0.6.20", features = [
    "form",
    "macros",
    "multipart",
    "headers",
] }
tower = { version = "0.4.13", features = [
    "tokio",
    "limit",
    "buffer",
    "timeout",
    "load-shed",
] }
thiserror = "1.0.49"
serde = { version = "1.0.188", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
sqlx = { version = "0.7.2", features = ["mysql", "runtime-tokio", "chrono"] }
hyper = { version = "0.14.27", features = ["full"] }
mimalloc = "0.1.39"
dashmap = "5.5.3"
chrono = "0.4.31"
serde_json = "1.0.107"
reqwest = "0.11.22"

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
