[package]
name = "heartbeat_api"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.33.0", features = ["full"] }
axum = { version = "0.6.20", features = ["macros", "multipart"] }
tower = { version = "0.4.13", features = [
    "tokio",
    "buffer",
    "timeout",
    "load-shed",
] }
thiserror = "1.0.50"
serde = { version = "1.0.192", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
sqlx = { version = "0.7.2", features = ["mysql", "runtime-tokio", "chrono"] }
hyper = { version = "1.0.0", features = ["full"] }
mimalloc = "0.1.39"
chrono = "0.4.31"
reqwest = { version = "0.11.22", features = ["json"] }
urlencoding = "2.1.3"
futures = "0.3.29"
ahash = "0.8.5"
serde_json = "1.0.108"
once_cell = "1.18.0"

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
