[package]
name = "heartbeat_api"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.35.0", features = ["full"] }
axum = { version = "0.7.2", features = ["macros", "multipart"] }
tower = { version = "0.4.13", features = [
    "tokio",
    "buffer",
    "timeout",
    "load-shed",
] }
thiserror = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio", "chrono"] }
hyper = { version = "1", features = ["full"] }
mimalloc = "0.1"
chrono = "0.4"
reqwest = { version = "0.11", features = ["json"] }
urlencoding = "2"
futures = "0.3"
ahash = "0.8"
serde_json = "1"
once_cell = "1"

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
